apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: billing
  name: billing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - env:
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: HTTPS_ENDPOINT
                  name: environment-variables
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  key: INSTANCE
                  name: environment-variables
            - name: ROCKETMQ_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: ROCKETMQ_ENDPOINTS
                  name: environment-variables
            - name: ROCKETMQ_ORDER_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: ROCKETMQ_ORDER_TOPIC
                  name: environment-variables
            - name: PROJECT
              valueFrom:
                configMapKeyRef:
                  key: PROJECT
                  name: environment-variables
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: ACCESS_KEY_ID
                  name: ak
            - name: ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  key: ACCESS_SECRET
                  name: ak
            - name: ROCKETMQ_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: ROCKETMQ_ACCESSKEY
                  name: ak
            - name: ROCKETMQ_SECRETKEY
              valueFrom:
                secretKeyRef:
                  key: ROCKETMQ_SECRETKEY
                  name: ak
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: aliyun_logs_application_tags
              value: application=order
          image: "sls-registry.cn-beijing.cr.aliyuncs.com/sls-mall/billing:1.0.0"
          imagePullPolicy: Always
          name: order
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
---
apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: order
  sessionAffinity: None
  type: ClusterIP
