apiVersion: v1
data:
  ACCESS_KEY_ID: WU9VUl9BQ0NFU1NfS0VZX0lE
  ACCESS_SECRET: WU9VUl9BQ0NFU1NfU0VDUkVU
  ROCKETMQ_ACCESSKEY: WU9VUl9BQ0NFU1NfS0VZX0lE
  ROCKETMQ_SECRETKEY: WU9VUl9BQ0NFU1NfU0VDUkVU
kind: Secret
metadata:
  name: ak
type: Opaque

---
apiVersion: v1
data:
  INTEGRAL_DB_DATABASE: aW50ZWdyYWw=
  MYSQL_ALLOW_EMPTY_PASSWORD: dHJ1ZQ==
  MYSQL_DATABASE: c29ja3NkYg==
  MYSQL_ROOT_PASSWORD: cm9vdA==
kind: Secret
metadata:
  name: mysql-config
type: Opaque

---
apiVersion: v1
data:
  dump.sql: "CREATE USER IF NOT EXISTS 'catalogue_user' IDENTIFIED BY 'default_password';\n\nGRANT ALL ON socksdb.* TO 'catalogue_user';\n\nCREATE TABLE IF NOT EXISTS sock (\n\tsock_id varchar(40) NOT NULL, \n\tname varchar(20), \n\tdescription varchar(200), \n\tprice float, \n\tcount int, \n\timage_url_1 varchar(40), \n\timage_url_2 varchar(40), \n\tPRIMARY KEY(sock_id)\n);\n\nCREATE TABLE IF NOT EXISTS tag (\n\ttag_id MEDIUMINT NOT NULL AUTO_INCREMENT, \n\tname varchar(20), \n\tPRIMARY KEY(tag_id)\n);\n\nCREATE TABLE IF NOT EXISTS sock_tag (\n\tsock_id varchar(40), \n\ttag_id MEDIUMINT NOT NULL, \n\tFOREIGN KEY (sock_id) \n\t\tREFERENCES sock(sock_id), \n\tFOREIGN KEY(tag_id)\n\t\tREFERENCES tag(tag_id)\n);\n\n\nINSERT INTO sock VALUES (\"6d62d909-f957-430e-8689-b5129c0bb75e\", \"Weave special\", \"Limited issue Weave socks.\", 17.15, 33, \"/catalogue/images/weave1.jpg\", \"/catalogue/images/weave2.jpg\");\nINSERT INTO sock VALUES (\"a0a4f044-b040-410d-8ead-4de0446aec7e\", \"Nerd leg\", \"For all those leg lovers out there. A perfect example of a swivel chair trained calf. Meticulously trained on a diet of sitting and Pina Coladas. Phwarr...\", 7.99, 115, \"/catalogue/images/bit_of_leg_1.jpeg\", \"/catalogue/images/bit_of_leg_2.jpeg\");\nINSERT INTO sock VALUES (\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\", \"Crossed\", \"A mature sock, crossed, with an air of nonchalance.\",  17.32, 738, \"/catalogue/images/cross_1.jpeg\", \"/catalogue/images/cross_2.jpeg\");\nINSERT INTO sock VALUES (\"510a0d7e-8e83-4193-b483-e27e09ddc34d\", \"SuperSport XL\", \"Ready for action. Engineers: be ready to smash that next bug! Be ready, with these super-action-sport-masterpieces. This particular engineer was chased away from the office with a stick.\",  15.00, 820, \"/catalogue/images/puma_1.jpeg\", \"/catalogue/images/puma_2.jpeg\");\nINSERT INTO sock VALUES (\"03fef6ac-1896-4ce8-bd69-b798f85c6e0b\", \"Holy\", \"Socks fit for a Messiah. You too can experience walking in water with these special edition beauties. Each hole is lovingly proggled to leave smooth edges. The only sock approved by a higher power.\",  99.99, 1, \"/catalogue/images/holy_1.jpeg\", \"/catalogue/images/holy_2.jpeg\");\nINSERT INTO sock VALUES (\"d3588630-ad8e-49df-bbd7-3167f7efb246\", \"YouTube.sock\", \"We were not paid to sell this sock. It's just a bit geeky.\",  10.99, 801, \"/catalogue/images/youtube_1.jpeg\", \"/catalogue/images/youtube_2.jpeg\");\nINSERT INTO sock VALUES (\"819e1fbf-8b7e-4f6d-811f-693534916a8b\", \"Figueroa\", \"enim officia aliqua excepteur esse deserunt quis aliquip nostrud anim\",  14, 808, \"/catalogue/images/WAT.jpg\", \"/catalogue/images/WAT2.jpg\");\nINSERT INTO sock VALUES (\"zzz4f044-b040-410d-8ead-4de0446aec7e\", \"Classic\", \"Keep it simple.\",  12, 127, \"/catalogue/images/classic.jpg\", \"/catalogue/images/classic2.jpg\");\nINSERT INTO sock VALUES (\"3395a43e-2d88-40de-b95f-e00e1502085b\", \"Colourful\", \"proident occaecat irure et excepteur labore minim nisi amet irure\",  18, 438, \"/catalogue/images/colourful_socks.jpg\", \"/catalogue/images/colourful_socks.jpg\");\nINSERT INTO sock VALUES (\"837ab141-399e-4c1f-9abc-bace40296bac\", \"Cat socks\", \"consequat amet cupidatat minim laborum tempor elit ex consequat in\",  15, 175, \"/catalogue/images/catsocks.jpg\", \"/catalogue/images/catsocks2.jpg\");\n\nINSERT INTO tag (name) VALUES (\"brown\");\nINSERT INTO tag (name) VALUES (\"geek\");\nINSERT INTO tag (name) VALUES (\"formal\");\nINSERT INTO tag (name) VALUES (\"blue\");\nINSERT INTO tag (name) VALUES (\"skin\");\nINSERT INTO tag (name) VALUES (\"red\");\nINSERT INTO tag (name) VALUES (\"action\");\nINSERT INTO tag (name) VALUES (\"sport\");\nINSERT INTO tag (name) VALUES (\"black\");\nINSERT INTO tag (name) VALUES (\"magic\");\nINSERT INTO tag (name) VALUES (\"green\");\n\nINSERT INTO sock_tag VALUES (\"6d62d909-f957-430e-8689-b5129c0bb75e\", \"2\");\nINSERT INTO sock_tag VALUES (\"6d62d909-f957-430e-8689-b5129c0bb75e\", \"9\");\nINSERT INTO sock_tag VALUES (\"a0a4f044-b040-410d-8ead-4de0446aec7e\", \"4\");\nINSERT INTO sock_tag VALUES (\"a0a4f044-b040-410d-8ead-4de0446aec7e\", \"5\");\nINSERT INTO sock_tag VALUES (\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\", \"4\");\nINSERT INTO sock_tag VALUES (\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\", \"6\");\nINSERT INTO sock_tag VALUES (\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\", \"7\");\nINSERT INTO sock_tag VALUES (\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\", \"3\");\nINSERT INTO sock_tag VALUES (\"510a0d7e-8e83-4193-b483-e27e09ddc34d\", \"8\");\nINSERT INTO sock_tag VALUES (\"510a0d7e-8e83-4193-b483-e27e09ddc34d\", \"9\");\nINSERT INTO sock_tag VALUES (\"510a0d7e-8e83-4193-b483-e27e09ddc34d\", \"3\");\nINSERT INTO sock_tag VALUES (\"03fef6ac-1896-4ce8-bd69-b798f85c6e0b\", \"10\");\nINSERT INTO sock_tag VALUES (\"03fef6ac-1896-4ce8-bd69-b798f85c6e0b\", \"7\");\nINSERT INTO sock_tag VALUES (\"d3588630-ad8e-49df-bbd7-3167f7efb246\", \"2\");\nINSERT INTO sock_tag VALUES (\"d3588630-ad8e-49df-bbd7-3167f7efb246\", \"3\");\nINSERT INTO sock_tag VALUES (\"819e1fbf-8b7e-4f6d-811f-693534916a8b\", \"3\");\nINSERT INTO sock_tag VALUES (\"819e1fbf-8b7e-4f6d-811f-693534916a8b\", \"11\");\nINSERT INTO sock_tag VALUES (\"819e1fbf-8b7e-4f6d-811f-693534916a8b\", \"4\");\nINSERT INTO sock_tag VALUES (\"zzz4f044-b040-410d-8ead-4de0446aec7e\", \"1\");\nINSERT INTO sock_tag VALUES (\"zzz4f044-b040-410d-8ead-4de0446aec7e\", \"11\");\nINSERT INTO sock_tag VALUES (\"3395a43e-2d88-40de-b95f-e00e1502085b\", \"1\");\nINSERT INTO sock_tag VALUES (\"3395a43e-2d88-40de-b95f-e00e1502085b\", \"4\");\nINSERT INTO sock_tag VALUES (\"837ab141-399e-4c1f-9abc-bace40296bac\", \"1\");\nINSERT INTO sock_tag VALUES (\"837ab141-399e-4c1f-9abc-bace40296bac\", \"11\");\nINSERT INTO sock_tag VALUES (\"837ab141-399e-4c1f-9abc-bace40296bac\", \"3\");\n\n\n\nDELIMITER && \nCREATE PROCEDURE selectTags(IN version varchar(20))\nBEGIN\n    declare sleepTime integer default 0;\n\n    /*Mock sleep time*/\n    if version = '1.3.0' then\n        set sleepTime = 1;\n    end if;\n\n    SELECT sleep(sleepTime), name from tag;\nend &&  \n\n "
kind: ConfigMap
metadata:
  name: mysql-configure
  annotations:
    app: mysql-configure

---
apiVersion: v1
data:
  dump.sql: |-
    CREATE TABLE IF NOT EXISTS anti_cheating_record
    (
        id          INT PRIMARY KEY AUTO_INCREMENT,
        type        LONG,
        original_id VARCHAR(1024),
        reason      VARCHAR(2048),
        user_id     VARCHAR(128),
        value       FLOAT,
        deleted     int,
        expire_time date,
        create_time date,
        update_time date
    );

    CREATE TABLE IF NOT EXISTS integral_recored
    (
        id          INT PRIMARY KEY AUTO_INCREMENT,
        type        LONG,
        original_id VARCHAR(1024),
        value       FLOAT,
        expire_time DATE,
        reason      VARCHAR(2048),
        user_id     VARCHAR(128),
        deleted     INT,
        create_time DATE,
        update_time DATE
    );

    CREATE TABLE IF NOT EXISTS reduce_integral
    (
        id          INT PRIMARY KEY AUTO_INCREMENT,
        reduce_id   LONG,
        add_id      LONG,
        value       FLOAT,
        expire_time DATE,
        user_id     VARCHAR(1024),
        deleted     INT,
        create_time DATE,
        update_time DATE
    );

    CREATE TABLE IF NOT EXISTS usable_integral
    (
        id          INT PRIMARY KEY AUTO_INCREMENT,
        record_id   LONG,
        value       FLOAT,
        expire_time DATE,
        user_id     VARCHAR(1024),
        deleted     INT,
        create_time DATE,
        update_time DATE
    );
kind: ConfigMap
metadata:
  name: integral-db-configure
---
apiVersion: v1
data:
  ENDPOINT: "project endpoint"
  HTTPS_ENDPOINT: "https://your_project_name.cn-beijing.log.aliyuncs.com:10010"
  INSTANCE: your_instance_id
  PROJECT: your_project_name
  REGION_ENDPOINT: cn-beijing.log.aliyuncs.com
  ROCKETMQ_ENDPOINTS: your_rocketmq_id.cn-beijing.rmq.aliyuncs.com:8080
  ROCKETMQ_ORDER_TOPIC: order-topic
kind: ConfigMap
metadata:
  name: environment-variables

---
apiVersion: v1
data:
  accounts-create.js: |-
    db.createCollection("addresses");
    db.createCollection("cards");
    db.createCollection("customers");
  address-insert.js: |
    function get_results(result) {
        print(tojson(result));
    }

    function insert_address(object) {
        print(db.addresses.insert(object));
    }

    insert_address({
        "_id": ObjectId("57a98d98e4b00679b4a830ad"),
        "number": "246",
        "street": "Whitelees Road",
        "city": "Glasgow",
        "postcode": "G67 3DL",
        "country": "United Kingdom"
    });
    insert_address({
        "_id": ObjectId("57a98d98e4b00679b4a830b0"),
        "number": "246",
        "street": "Whitelees Road",
        "city": "Glasgow",
        "postcode": "G67 3DL",
        "country": "United Kingdom"
    });
    insert_address({
        "_id": ObjectId("57a98d98e4b00679b4a830b3"),
        "number": "4",
        "street": "Maes-Y-Deri",
        "city": "Aberdare",
        "postcode": "CF44 6TF",
        "country": "United Kingdom"
    });
    insert_address({
        "_id": ObjectId("57a98ddce4b00679b4a830d1"),
        "number": "3",
        "street": "my road",
        "city": "London",
        "country": "UK"
    });

    print("________ADDRESS DATA_______");
    db.addresses.find().forEach(get_results);
    print("______END ADDRESS DATA_____");
  card-insert.js: |+
    function get_results(result) {
        print(tojson(result));
    }

    function insert_card(object) {
        print(db.cards.insert(object));
    }

    insert_card({
        "_id": ObjectId("57a98d98e4b00679b4a830ae"),
        "longNum": "5953580604169678",
        "expires": "08/19",
        "ccv": "678"
    });
    insert_card({
        "_id": ObjectId("57a98d98e4b00679b4a830b1"),
        "longNum": "5544154011345918",
        "expires": "08/19",
        "ccv": "958"
    });
    insert_card({
        "_id": ObjectId("57a98d98e4b00679b4a830b4"),
        "longNum": "0908415193175205",
        "expires": "08/19",
        "ccv": "280"
    });
    insert_card({
        "_id": ObjectId("57a98ddce4b00679b4a830d2"),
        "longNum": "5429804235432",
        "expires": "04/16",
        "ccv": "432"
    });

    print("________CARD DATA_______");
    db.cards.find().forEach(get_results);
    print("______END CARD DATA_____");


  customer-insert.js: |
    function get_results(result) {
        print(tojson(result));
    }

    function insert_customer(object) {
        print(db.customers.insert(object));
    }

    insert_customer({
        "_id": ObjectId("57a98d98e4b00679b4a830af"),
        "firstName": "Eve",
        "lastName": "Berger",
        "username": "Eve_Berger",
        "password": "fec51acb3365747fc61247da5e249674cf8463c2",
        "salt": "c748112bc027878aa62812ba1ae00e40ad46d497",
        "addresses": [ObjectId("57a98d98e4b00679b4a830ad")],
        "cards": [ObjectId("57a98d98e4b00679b4a830ae")]
    });
    //pass eve
    insert_customer({
        "_id": ObjectId("57a98d98e4b00679b4a830b2"),
        "firstName": "User",
        "lastName": "Name",
        "username": "user",
        "password": "e2de7202bb2201842d041f6de201b10438369fb8",
        "salt": "6c1c6176e8b455ef37da13d953df971c249d0d8e",
        "addresses": [ObjectId("57a98d98e4b00679b4a830b0")],
        "cards": [ObjectId("57a98d98e4b00679b4a830b1")]
    });
    //pass password
    insert_customer({
        "_id": ObjectId("57a98d98e4b00679b4a830b5"),
        "firstName": "User1",
        "lastName": "Name1",
        "username": "user1",
        "password": "8f31df4dcc25694aeb0c212118ae37bbd6e47bcd",
        "salt": "bd832b0e10c6882deabc5e8e60a37689e2b708c2",
        "addresses": [ObjectId("57a98d98e4b00679b4a830b3")],
        "cards": [ObjectId("57a98d98e4b00679b4a830b4")]
    });
    //pass passsord
    print("_______CUSTOMER DATA_______");
    db.customers.find().forEach(get_results);
    print("______END CUSTOMER DATA_____");
kind: ConfigMap
metadata:
  name: mongo-configure

---

