apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8088"
        prometheus.io/scrape: "true"
      labels:
        app: shipping
    spec:
      containers:
        - env:
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: HTTPS_ENDPOINT
                  name: environment-variables
            - name: INSTANCE
              valueFrom:
                configMapKeyRef:
                  key: INSTANCE
                  name: environment-variables
            - name: PROJECT
              valueFrom:
                configMapKeyRef:
                  key: PROJECT
                  name: environment-variables
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: ACCESS_KEY_ID
                  name: ak
            - name: ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  key: ACCESS_SECRET
                  name: ak
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: aliyun_logs_application_tags
              value: application=shipping
          image: "dandylion98/sls-mall-shipping:v1"
          imagePullPolicy: Always
          name: shipping
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8088
  selector:
    app: shipping
  sessionAffinity: None
  type: ClusterIP
