create_namespace:
	kubectl create namespace opentelemetry

install_configmap:
	kubectl apply -f opentelemetry-configmap.yaml

start_opentelemetry_java_demo:
	kubectl apply -f opentelemetry-java.yaml

start_opentelemetry_dotnet_demo:
	kubectl apply -f opentelemetry-dotnet.yaml

start_opentelemetry_go_demo:
	kubectl apply -f opentelemetry-go.yaml

start_opentelemetry_php_demo:
	kubectl apply -f opentelemetry-php.yaml

start_opentelemetry_python_demo:
	kubectl apply -f opentelemetry-python.yaml

start_opentelemetry_node_demo:
	kubectl apply -f opentelemetry-node.yaml
