apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-php
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: opentelemetry-php
  template:
    metadata:
      labels:
        demo: opentelemetry-php
    spec:
      containers:
      - name: opentelemetry-php
        image: sls-registry.cn-beijing.cr.aliyuncs.com/sls-mis/opentelemetry-php
        envFrom:
        - configMapRef:
            name: environment-variables
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-php
  namespace: opentelemetry
spec:
  type: NodePort
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    nodePort: 30006
  selector:
    demo: opentelemetry-php
