apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-python
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: opentelemetry-python
  template:
    metadata:
      labels:
        demo: opentelemetry-python
    spec:
      containers:
      - name: opentelemetry-python
        image: sls-registry.cn-beijing.cr.aliyuncs.com/sls-mis/opentelemetry-python
        envFrom:
        - configMapRef:
            name: environment-variables
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-python
  namespace: opentelemetry
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    nodePort: 30007
  selector:
    demo: opentelemetry-python
