java_demo := ./opentelemetry-java
dotnet_demo := ./opentelemetry-dotnet
go_demo := ./opentelemetry-go
node_demo := ./opentelemetry-node
php_demo := ./opentelemetry-php
python_demo := ./opentelemetry-python
