[components]
opentelemetry-java=localhost:8081
opentelemetry-go=localhost:8082

[steps.start]
goto=opentelemetry-java
next_path=step1

[steps.step1]
goto=opentelemetry-java
next_path=step2

[steps.step2]
goto=openetelemetry-go
next_path=step3

[[steps.step3]]
goto=opentelemetry-java
next_path=step4

[[steps.step3]]
goto=opentelemetry-go
next_path=NULL
