INSERT INTO T_CUSTOMER (name)
VALUES ('TEST1');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST2');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST3');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST4');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST5');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST6');

INSERT INTO T_CUSTOMER (name)
VALUES ('TEST7');